module.exports = function (app) {
  // Imports
  let Queue = require('./Queue.js')
  let queue = new Queue()

  // add beacons na fila
  app.get('/add/:data', (req, res) => {
    queue.add(req.params.data)
    res.send({ msg: 'inserido' })
  })

  // add lista de beacons na fila
  app.get('/addAll/:data', (req, res) => {
    console.log("CHEGOU REQUEST: " + req.params.data)
    res.send({ msg: 'inserido' })
  })

  app.post('/postAll', (req, res) => {
    console.log("CHEGOU REQUEST: " + req.params.data)
    res.send({ msg: 'inserido' })
  })
  
  // Remove o primeiro dado da fila
  app.get('/remove', (req, res) => {
    let data = queue.remove()
  
    if (data) {
      res.send(data);
    } else {
      res.send({ beacons: null })
    }
  })

  // Rota para limpar fila
  app.get('/reset', (req, res) => {
    queue.reset()
    res.send({ msg: 'resetada' })
  })
  
  // Rota para pegar todos os dados da queue (nao remove)
  app.get('/show', (req, res) => {
    let data = queue.show()
  
    if (data) {
      res.send({ queue: data });
    } else {
      res.send({ queue: null })
    }
  })
  
  // Rota para inserir dados de teste na queue
  app.get('/test', (req, res) => {
    for (let i = 1; i < 100; i++) {
      let b = [
        {
          id: 'beacon_amarelo',
          dist: i * 3.4
        },
        {
          id: 'beacon_rosa',
          dist: i * 12.5
        },
        {
          id: 'beacon_roxo',
          dist: i * 2.7
        }
      ]
      queue.add({ beacons: b })
    }
    res.send(queue.show())
  })

  app.get('/testRealData', (req, res) => {
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 92 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 87 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 87 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 92 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 92 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 92 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 91 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 91 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 86} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 89 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 89 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 87 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 92 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 91} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 90 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 88 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 89} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 90 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 91 }, { id: "beacon_rosa", dist: 87 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 90} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 85 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 90 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 89 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 89 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 85} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 92 }, { id: "beacon_rosa", dist: 86 }, { id: "beacon_roxo", dist: 92 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 86 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 86 } ]})
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 85 }, { id: "beacon_rosa", dist: 85 }, { id: "beacon_roxo", dist: 88} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 91 }, { id: "beacon_roxo", dist: 92} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 88 }, { id: "beacon_rosa", dist: 88 }, { id: "beacon_roxo", dist: 87} ] })
    queue.add({ beacons: [{ id: "beacon_amarelo", dist: 87 }, { id: "beacon_rosa", dist: 92 }, { id: "beacon_roxo", dist: 86 } ]})
    res.send(queue.show())
})

}